java -jar dist\ThreadingDemo.jar 708 1 > demo.txt
java -jar dist\ThreadingDemo.jar 708 2 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 3 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 4 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 5 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 6 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 7 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 8 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 9 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 10 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 11 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 12 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 13 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 14 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 15 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 16 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 17 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 18 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 19 >> demo.txt
java -jar dist\ThreadingDemo.jar 708 20 >> demo.txt